# Generated by Django 5.2.1 on 2025-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('jumlah', models.PositiveIntegerField()),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal_ditambahkan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
