# Generated by Django 5.2 on 2025-06-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barang", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nama Kategori"
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(
                        blank=True, null=True, verbose_name="Deskripsi Kategori"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kategori",
            },
        ),
        migrations.AddField(
            model_name="barang",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barang",
                to="barang.kategori",
            ),
        ),
    ]
